// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(DeliverContext))]
    [Migration("20231108121008_SeededData")]
    partial class SeededData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Models.Menu", b =>
                {
                    b.Property<string>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MenuDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MenuNutrience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuPrepTime")
                        .HasColumnType("int");

                    b.Property<decimal>("MenuPrice")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("MenuId");

                    b.HasIndex("MenuName")
                        .IsUnique()
                        .HasFilter("[MenuName] IS NOT NULL");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            MenuId = "1",
                            MenuDescription = "Best fried chicken in town",
                            MenuImage = "",
                            MenuName = "Fried Chicken",
                            MenuNutrience = "260kcal",
                            MenuPrepTime = 15,
                            MenuPrice = 10.99m
                        },
                        new
                        {
                            MenuId = "2",
                            MenuDescription = "juicy hamburger with cheese",
                            MenuImage = "",
                            MenuName = "Hamburger",
                            MenuNutrience = "491kcal",
                            MenuPrepTime = 10,
                            MenuPrice = 12.99m
                        },
                        new
                        {
                            MenuId = "3",
                            MenuDescription = "Premium Russet Burbank variety potatoes for that fluffy inside, crispy outside taste",
                            MenuImage = "",
                            MenuName = "Fries",
                            MenuNutrience = "432kcal",
                            MenuPrepTime = 8,
                            MenuPrice = 4.99m
                        });
                });

            modelBuilder.Entity("DataAccess.Models.MenuCategory", b =>
                {
                    b.Property<string>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MenuId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CategoryId");

                    b.HasIndex("Category")
                        .IsUnique()
                        .HasFilter("[Category] IS NOT NULL");

                    b.HasIndex("MenuId");

                    b.ToTable("MenuCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = "1",
                            Category = "Burgers",
                            MenuId = "2"
                        },
                        new
                        {
                            CategoryId = "2",
                            Category = "Sides",
                            MenuId = "3"
                        },
                        new
                        {
                            CategoryId = "3",
                            Category = "Chicken",
                            MenuId = "1"
                        });
                });

            modelBuilder.Entity("DataAccess.Models.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.Property<string>("UserAddressId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrderId");

                    b.HasIndex("UserAddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = "1",
                            OrderDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 33,
                            UserAddressId = "1",
                            UserId = "1"
                        },
                        new
                        {
                            OrderId = "2",
                            OrderDate = new DateTime(2023, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 26,
                            UserAddressId = "2",
                            UserId = "1"
                        },
                        new
                        {
                            OrderId = "3",
                            OrderDate = new DateTime(2023, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 17,
                            UserAddressId = "2",
                            UserId = "1"
                        },
                        new
                        {
                            OrderId = "4",
                            OrderDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 88,
                            UserAddressId = "1",
                            UserId = "1"
                        },
                        new
                        {
                            OrderId = "5",
                            OrderDate = new DateTime(2023, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 43,
                            UserAddressId = "3",
                            UserId = "3"
                        });
                });

            modelBuilder.Entity("DataAccess.Models.OrderItem", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MenuId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            OrderId = "4",
                            MenuId = "3",
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = "5",
                            MenuId = "1",
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = "2",
                            MenuId = "2",
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = "1",
                            MenuId = "1",
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = "1",
                            MenuId = "2",
                            Quantity = 5
                        },
                        new
                        {
                            OrderId = "3",
                            MenuId = "3",
                            Quantity = 6
                        },
                        new
                        {
                            OrderId = "2",
                            MenuId = "3",
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("DataAccess.Models.Review", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderItemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderedItemMenuId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderedItemOrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ReviewRating")
                        .HasPrecision(1)
                        .HasColumnType("decimal(1,0)");

                    b.Property<string>("ReviewText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "OrderItemId");

                    b.HasIndex("OrderedItemOrderId", "OrderedItemMenuId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            OrderItemId = "1",
                            ReviewRating = 5m,
                            ReviewText = "The food taste like food, Good!"
                        },
                        new
                        {
                            UserId = "1",
                            OrderItemId = "2",
                            ReviewRating = 3m,
                            ReviewText = "In a small chapel, known as the Morning Chapel"
                        },
                        new
                        {
                            UserId = "3",
                            OrderItemId = "2",
                            ReviewRating = 1m,
                            ReviewText = "The Organ,which is placed above the screen, dividing the nave from the choir"
                        });
                });

            modelBuilder.Entity("DataAccess.Models.User", b =>
                {
                    b.Property<string>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = "1",
                            Email = "email1@gmail.com",
                            Username = "User1"
                        },
                        new
                        {
                            UserID = "2",
                            Email = "nberzon0@wordpress.org",
                            PasswordHash = "",
                            Username = "nyablsley0"
                        },
                        new
                        {
                            UserID = "3",
                            Email = "spappin1@163.com",
                            PasswordHash = "",
                            Username = "kburgott1"
                        },
                        new
                        {
                            UserID = "4",
                            Email = "mlawee2@pen.io",
                            PasswordHash = "",
                            Username = "gmcanalley2"
                        },
                        new
                        {
                            UserID = "5",
                            Email = "eu.erat.semper@protonmail.org",
                            PasswordHash = "",
                            Username = "larpin3@nasa.gov"
                        });
                });

            modelBuilder.Entity("DataAccess.Models.UserAddress", b =>
                {
                    b.Property<string>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddressLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AddressId");

                    b.HasIndex("Address")
                        .IsUnique()
                        .HasFilter("[Address] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddresses");

                    b.HasData(
                        new
                        {
                            AddressId = "1",
                            Address = "Suite 56 49047 Holmberg Parkway",
                            AddressLabel = "Home address",
                            UserId = "1"
                        },
                        new
                        {
                            AddressId = "2",
                            Address = "PO Box 95686 7324 Acker Place",
                            AddressLabel = "Word address",
                            UserId = "1"
                        },
                        new
                        {
                            AddressId = "3",
                            Address = "Apt 510 97 Southridge Hill",
                            AddressLabel = "Friend address",
                            UserId = "3"
                        });
                });

            modelBuilder.Entity("DataAccess.Models.UserPaymentDetails", b =>
                {
                    b.Property<string>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("CardNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameOnCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CardId");

                    b.HasIndex("CardNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserPaymentDetails");

                    b.HasData(
                        new
                        {
                            CardId = "1",
                            CardNumber = 5020751290843793L,
                            ExpiryDate = new DateTime(2024, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameOnCard = "Rebekah Matevushev",
                            PaymentAddress = "50 Graceland Avenue, Room 871",
                            UserId = "1"
                        },
                        new
                        {
                            CardId = "2",
                            CardNumber = 6331105501692333L,
                            ExpiryDate = new DateTime(2025, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameOnCard = "Henrik Cheves",
                            PaymentAddress = "56 Becker Hill, Apt 814",
                            UserId = "2"
                        },
                        new
                        {
                            CardId = "3",
                            CardNumber = 5100179478445091L,
                            ExpiryDate = new DateTime(2027, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameOnCard = "Mitchel	0785 Maple Drive, Ulrica Rikel",
                            PaymentAddress = "Apt 1652",
                            UserId = "2"
                        });
                });

            modelBuilder.Entity("DataAccess.Models.MenuCategory", b =>
                {
                    b.HasOne("DataAccess.Models.Menu", "Menu")
                        .WithMany("MenuCategories")
                        .HasForeignKey("MenuId");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("DataAccess.Models.Order", b =>
                {
                    b.HasOne("DataAccess.Models.UserAddress", "UserAddress")
                        .WithMany("Orders")
                        .HasForeignKey("UserAddressId");

                    b.HasOne("DataAccess.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("User");

                    b.Navigation("UserAddress");
                });

            modelBuilder.Entity("DataAccess.Models.OrderItem", b =>
                {
                    b.HasOne("DataAccess.Models.Menu", "Menu")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DataAccess.Models.Review", b =>
                {
                    b.HasOne("DataAccess.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Models.OrderItem", "OrderedItem")
                        .WithMany("Reviews")
                        .HasForeignKey("OrderedItemOrderId", "OrderedItemMenuId");

                    b.Navigation("OrderedItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccess.Models.UserAddress", b =>
                {
                    b.HasOne("DataAccess.Models.User", "User")
                        .WithMany("UserAddresses")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccess.Models.UserPaymentDetails", b =>
                {
                    b.HasOne("DataAccess.Models.User", "User")
                        .WithMany("UserPaymentDetails")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccess.Models.Menu", b =>
                {
                    b.Navigation("MenuCategories");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("DataAccess.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("DataAccess.Models.OrderItem", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("DataAccess.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("UserAddresses");

                    b.Navigation("UserPaymentDetails");
                });

            modelBuilder.Entity("DataAccess.Models.UserAddress", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
